### ISSUE TITLE
css not cached?

### ISSUE THREAD

**Issue by eileenmcnaughton** [djfm/cssin#2]
The getCSS function says it caches the files but I believe it needs to refer to self::cssFiles rather than just $cssFiles for this to be true - it seems to be just using a locally scoped non-static var

```
    if(!isset($cssFiles[$url]))
    {
        $cssFiles[$url] = file_get_contents($url);
    }
    return $cssFiles[$url];
```

https://github.com/djfm/cssin/blob/master/src/CSSIN.php#L32

**Comment by djfm** [comment]
It caches css files per instance of cssin, that's the current intended behaviour, as the original goal is to speed-up the inilining of a bunch of files sharing the same CSS (say, a bunch of e-mail templates for instance).
