### ISSUE TITLE
Switch to an FSF or OSI-approved free software license

### ISSUE THREAD

**Issue by williamtheaker** [djfm/cssin#4]
I'd like to use this with CiviCRM, but the license for cssin is too vague. Have you considered switching to a GPL-compatible license?

FSF approved licenses: https://gnu.org/licenses/license-list.html#SoftwareLicenses
OSI approved licenses: http://opensource.org/licenses/alphabetical

**Comment by djfm** [comment]
Hi, i'd be happy to see cssin used by CiviCRM, I've switched to GPLv3 (seems like the only option because the dependencies are licensed under MIT (csstidy) and GPL (simple_html_dom).
